<?php $basedir = dirname( __FILE__ );
require_once($basedir.'/../../../Connections/sporteqa.php');?>
<?php

// Set the uplaod directory
$targetFolder = '/userfiles/user';

function errorHandler($errno, $errstr, $errfile, $errline) {
	// In this script, the silently suppress any error generated by getimagesize
	// which will throw an error if the "image" isn't an image
	// ie doesn't have a valid width / height

    /* Don't execute PHP internal error handler */
    return true;
}

$old_error_handler = set_error_handler("errorHandler");

// Check if the file has a width and height
function isImage($tempFile) {

	// Get the size of the image
    $size = getimagesize($tempFile);

	if (isset($size) && $size[0] && $size[1] && $size[0] *  $size[1] > 0) {
		return true;
	} else {
		return false;
	}

}
function imageList($tempFile){
	$size = array_values(getimagesize($tempFile));
	return list($width, $height, $type, $attr) = $size;
}
function imageType($type){
	return image_type_to_mime_type($type);
}
class Image {
				
            
            var $uploaddir;
            var $quality = 80;
            var $ext;
            var $dst_r;
            var $img_r;
            var $img_w;
            var $img_h;
            var $output;
            var $data;
            var $datathumb;
            
            function setFile($src = null) {
	
                $this->ext = strtoupper(pathinfo($src, PATHINFO_EXTENSION));
                if(is_file($src) && ($this->ext == "JPG" OR $this->ext == "JPEG")) {
                    $this->img_r = ImageCreateFromJPEG($src);
                } elseif(is_file($src) && $this->ext == "PNG") {
                    $this->img_r = ImageCreateFromPNG($src);      
                } elseif(is_file($src) && $this->ext == "GIF") {
                    $this->img_r = ImageCreateFromGIF($src);
                }
                $this->img_w = imagesx($this->img_r);
                $this->img_h = imagesy($this->img_r);
            }
            
            function resize($w = 100) {
                $h =  $this->img_h / ($this->img_w / $w);
                $this->dst_r = ImageCreateTrueColor($w, $h);
                imagecopyresampled($this->dst_r, $this->img_r, 0, 0, 0, 0, $w, $h, $this->img_w, $this->img_h);
                $this->img_r = $this->dst_r;
                $this->img_h = $h;
                $this->img_w = $w;
            }
            
            function createFile($output_filename = null) {
                if($this->ext == "JPG" OR $this->ext == "JPEG") {
                    imageJPEG($this->dst_r, $this->uploaddir.$output_filename.'.'.strtolower($this->ext), $this->quality);
                } elseif($this->ext == "PNG") {
                    imagePNG($this->dst_r, $this->uploaddir.$output_filename.'.'.strtolower($this->ext));
                } elseif($this->ext == "GIF") {
                    imageGIF($this->dst_r, $this->uploaddir.$output_filename.'.'.strtolower($this->ext));
                }
                $this->output = $this->uploaddir.$output_filename.'.'.strtolower($this->ext);
				//echo $this->output;
            }
            
            function setUploadDir($dirname) {
                $this->uploaddir = $dirname;
            }
            
            function flush() {
				$targetFolder = '/userfiles/user';

				$tempFile = $_FILES['Filedata']['tmp_name'];
				$targetPath = $_SERVER['DOCUMENT_ROOT'] . $targetFolder.'/';
				$targetFile =  str_replace('//','/',$targetPath) . $_FILES['Filedata']['name'];
				$ext = strtoupper(pathinfo($targetFile, PATHINFO_EXTENSION));
				$fileEnc = md5($tempFile).".".strtolower($ext);
				$targetFileEnc =  str_replace('//','/',$targetPath) . $fileEnc;
                
                imagedestroy($this->dst_r);
                unlink($targetFileEnc);
                //imagedestroy($this->img_r);
                
            }
            
        }

if (!empty($_FILES)) {

	$fileData = $_FILES['Filedata'];

	if ($fileData) {
		$tempFile   = $fileData['tmp_name'];
		$targetPath = $_SERVER['DOCUMENT_ROOT'] . $targetFolder . '/';
		$targetFile = rtrim($targetPath,'/') . '/' . $_FILES['Filedata']['name'];
		
		

		// Validate the file type
		$fileTypes = array('png', 'jpg', 'gif','jpeg'); // Allowed file extensions
		$fileParts = pathinfo($fileData['name']);

		// Validate the filetype
		if (in_array(strtolower($fileParts['extension']), $fileTypes) && filesize($tempFile) > 0 && isImage($tempFile)) {
		
	

			$id = $_REQUEST['id_page'];
			$file_modby = $_REQUEST['modby'];
			$file_moddate = $_REQUEST['moddate'];
			
			$targetFolder = '/userfiles/user';

			$tempFile = $_FILES['Filedata']['tmp_name'];
			$targetPath = $_SERVER['DOCUMENT_ROOT'] . $targetFolder.'/';
			$targetFile =  str_replace('//','/',$targetPath) . $_FILES['Filedata']['name'];
			$ext = strtoupper(pathinfo($targetFile, PATHINFO_EXTENSION));
			$fileEnc = md5($tempFile).".".strtolower($ext);
			$targetFileEnc =  str_replace('//','/',$targetPath) . $fileEnc;
			
			move_uploaded_file($tempFile, $targetFileEnc);	
			
			$insertSQL = sprintf("INSERT INTO spq_registration_data (spq_registration_data_distance, spq_registration_data_user_id, spq_registration_data_file, spq_registration_data_time, spq_registration_data_modby, spq_registration_id, spq_registration_data_date) VALUES (%s,%s,%s,%s,%s,%s,%s)",
			
                       GetSQLValueString($_REQUEST['spq_distance'], "double"),
                       GetSQLValueString($_REQUEST['spq_id'], "int"),
                       GetSQLValueString(md5($tempFile).".".strtolower($ext), "text"),
					   GetSQLValueString(time(), "int"),
					   GetSQLValueString($_REQUEST['spq_fullname'], "text"),
					   GetSQLValueString($_REQUEST['spq_regid'], "int"),
					   GetSQLValueString(strtotime($_REQUEST['spq_date_register']), "int"));
			
			mysqli_select_db( $sporteqa, $database_sporteqa); //echo $insertSQL;
			$Result1 = mysqli_query( $sporteqa, $insertSQL) or die(mysqli_error($sporteqa));
			
			
			
	    
	
		$image = new Image();
        $image->setFile($targetFileEnc);
        $image->setUploadDir($targetPath);
		
        $image->resize(1024);
        $image->createFile("l_".md5($tempFile));
		$image->resize(640);
        $image->createFile("m_".md5($tempFile));
        $image->resize(100);
        $image->createFile("s_".md5($tempFile));

			
			//$image->flush();
	
			
			// Save the file
			//move_uploaded_file($tempFile, $targetFileEnc);
			
		} else {

			// The file type wasn't allowed
			echo 'Invalid file type.';
		}
	}
}
?>