<?php $basedir = dirname( __FILE__ );
require_once($basedir.'/../../../Connections/sporteqa.php'); ?>
<?php 
/*
UploadiFive
Copyright (c) 2012 Reactive Apps, Ronnie Garcia
*/

/*
IMPORTANT: This script requires the PHP GD library
*/

// Set the uplaod directory
$uploadDir = '/userfiles/file/';

function errorHandler($errno, $errstr, $errfile, $errline) {
	// In this script, the silently suppress any error generated by getimagesize
	// which will throw an error if the "image" isn't an image
	// ie doesn't have a valid width / height

    /* Don't execute PHP internal error handler */
    return true;
}

$old_error_handler = set_error_handler("errorHandler");

// Check if the file has a width and height
function isImage($tempFile) {

	// Get the size of the image
    $size = getimagesize($tempFile);

	if (isset($size) && $size[0] && $size[1] && $size[0] *  $size[1] > 0) {
		return true;
	} else {
		return false;
	}

}
function imageList($tempFile){
	$size = array_values(getimagesize($tempFile));
	return list($width, $height, $type, $attr) = $size;
}
function imageType($type){
	return image_type_to_mime_type($type);
}

if (!empty($_FILES)) {

	$fileData = $_FILES['Filedata'];

	if ($fileData) {
		$tempFile   = $fileData['tmp_name'];
		$uploadDir  = $_SERVER['DOCUMENT_ROOT'] . $uploadDir;
		$targetFile = $uploadDir . $fileData['name'];
		

		// Validate the file type
		$fileTypes = array('pdf', 'doc', 'docx', 'xls', 'xlsx'); // Allowed file extensions
		$fileParts = pathinfo($fileData['name']);

		// Validate the filetype
		if (in_array(strtolower($fileParts['extension']), $fileTypes) && filesize($tempFile) > 0) {
			
			$ext = $fileParts['extension'];
			$target_filename = md5($fileData['name'].time()).".".$ext;
			$target_file = $uploadDir.$target_filename;
			
			$id = $_REQUEST['spq_file_id'];
			$file_modby = $_REQUEST['modby'];
			$file_moddate = $_REQUEST['moddate'];
			
			// insert xs_file with relevant document info
			$updateSQL = sprintf("INSERT INTO xs_file (spq_file_id, file_name, file_type, file_date, file_modby, spq_event_id, spq_event_registration_id, spq_event_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)",
				     GetSQLValueString($id, "int"),
					 GetSQLValueString($target_filename, "text"),
				    GetSQLValueString(1, "int"),
					GetSQLValueString($file_moddate, "int"),
					GetSQLValueString($file_modby , "text"),
					GetSQLValueString($_POST['spq_event_id'], "text"),
					GetSQLValueString($_POST['spq_event_registration_id'], "text"),
					GetSQLValueString($_POST['spq_event_user_id'], "text"));
		mysqli_select_db( $sporteqa, $database_sporteqa); 
		$Result1 = mysqli_query( $sporteqa, $updateSQL) or die(mysqli_error($sporteqa));
			
			//echo "Result:".$Result1;
			
			// Save the file
			move_uploaded_file($tempFile, $target_file);
			
		} else {

			// The file type wasn't allowed
			echo 'Invalid file type.';
		}
	}
}
?>