<?php require_once('../../Connections/sporteqa_nologin.php'); ?>
<?php
/*
UploadiFive
Copyright (c) 2012 Reactive Apps, Ronnie Garcia
*/

/*
IMPORTANT: This script requires the PHP GD library
*/
if (!function_exists("GetSQLValueString")) {
function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  if (PHP_VERSION < 6) {
    $theValue = get_magic_quotes_gpc() ? stripslashes($theValue) : $theValue;
  }

  $theValue = function_exists("mysqli_real_escape_string") ? mysqli_real_escape_string($sporteqa, $theValue) : ((isset($sporteqa) && is_object($sporteqa)) ? mysqli_real_escape_string($sporteqa, $theValue) : ((trigger_error($sporteqa, E_USER_ERROR)) ? "" : ""));

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? doubleval($theValue) : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}
}
// Set the uplaod directory
$uploadDir = '/userfiles/setup/';

function errorHandler($errno, $errstr, $errfile, $errline) {
	// In this script, the silently suppress any error generated by getimagesize
	// which will throw an error if the "image" isn't an image
	// ie doesn't have a valid width / height

    /* Don't execute PHP internal error handler */
    return true;
}

$old_error_handler = set_error_handler("errorHandler");

// Check if the file has a width and height
function isImage($tempFile) {

	// Get the size of the image
    $size = getimagesize($tempFile);

	if (isset($size) && $size[0] && $size[1] && $size[0] *  $size[1] > 0) {
		return true;
	} else {
		return false;
	}

}
function imageList($tempFile){
	$size = array_values(getimagesize($tempFile));
	return list($width, $height, $type, $attr) = $size;
}
function imageType($type){
	return image_type_to_mime_type($type);
}

if (!empty($_FILES)) {

	$fileData = $_FILES['Filedata'];

	if ($fileData) {
		$tempFile   = $fileData['tmp_name'];
		$uploadDir  = $_SERVER['DOCUMENT_ROOT'] . $uploadDir;
		$targetFile = $uploadDir . $fileData['name'];
		$targetFileHTTP = "http://".$_SERVER['SERVER_NAME'] . $uploadDir . $fileData['name'];

		// Validate the file type
		$fileTypes = array('jpg', 'jpeg', 'gif', 'png'); // Allowed file extensions
		$fileParts = pathinfo($fileData['name']);

		// Validate the filetype
		if (in_array(strtolower($fileParts['extension']), $fileTypes) && filesize($tempFile) > 0 && isImage($tempFile)) {
			
			
			
			// update xs_setup with relevant image info
			$updateSQL = sprintf("UPDATE xs_setup SET site_image=%s, site_image_width=%s, site_image_height=%s, site_image_type=%s WHERE idxs_setup = 1",
				    GetSQLValueString($fileData['name'], "text"),
				    GetSQLValueString(imageList($targetFile)[0], "int"),
					GetSQLValueString(imageList($targetFile)[1], "int"),
					GetSQLValueString(imageList($targetFile)[6], "text"));
		mysqli_select_db( $sporteqa, $database_sporteqa); //echo $updateSQL;
		$Result1 = mysqli_query( $sporteqa, $updateSQL) or die(mysqli_error($sporteqa));
			
			//echo "Result:".$Result1;
			
			// Save the file
			move_uploaded_file($tempFile, $targetFile);
			
		} else {

			// The file type wasn't allowed
			echo 'Invalid file type.';
		}
	}
}
?>