<?php
require_once(__DIR__.'/../../../Connections/exsite.php');

//ini_set('display_errors', 1); ini_set('display_startup_errors', 1); error_reporting(E_ALL);
// Set the uplaod directory
$uploadDir = $_SESSION['account_folder'].'/userfiles/user/'.$_SESSION['account_id'].'/images/';
function errorHandler($errno, $errstr, $errfile, $errline) {
	// In this script, the silently suppress any error generated by getimagesize
	// which will throw an error if the "image" isn't an image
	// ie doesn't have a valid width / height
    /* Don't execute PHP internal error handler */
    return true;
}
$old_error_handler = set_error_handler("errorHandler");
// Check if the file has a width and height
function isImage($tempFile) {
	// Get the size of the image
    $size = getimagesize($tempFile);
	if (isset($size) && $size[0] && $size[1] && $size[0] *  $size[1] > 0) {
		return true;
	} else {
		return false;
	}
}
function imageList($tempFile){
	$size = array_values(getimagesize($tempFile));
	return list($width, $height, $type, $attr) = $size;
}
function imageType($type){
	return image_type_to_mime_type($type);
}
class Image {
				
            
            var $uploaddir;
            var $quality = 80;
            var $ext;
            var $dst_r;
            var $img_r;
            var $img_w;
            var $img_h;
            var $output;
            var $data;
            var $datathumb;
            
            function setFile($src = null) {
	
                $this->ext = strtoupper(pathinfo($src, PATHINFO_EXTENSION));
                if(is_file($src) && ($this->ext == "JPG" OR $this->ext == "JPEG")) {
                    $this->img_r = ImageCreateFromJPEG($src);
                } elseif(is_file($src) && $this->ext == "PNG") {
                    $this->img_r = ImageCreateFromPNG($src);      
                } elseif(is_file($src) && $this->ext == "GIF") {
                    $this->img_r = ImageCreateFromGIF($src);
                }
                $this->img_w = imagesx($this->img_r);
                $this->img_h = imagesy($this->img_r);
            }
            
            function resize($w) {
                $h =  $this->img_h / ($this->img_w / $w);
                $this->dst_r = ImageCreateTrueColor($w, $h);
                imagecopyresampled($this->dst_r, $this->img_r, 0, 0, 0, 0, $w, $h, $this->img_w, $this->img_h);
	
				/*if ($w==1024){
					$watermark = imagecreatefrompng('agriquip-logo-xxx.png');
					$watermarkX = imagesx($watermark);
					$watermarkY = imagesy($watermark);
					imagecopy($this->dst_r, $watermark, 10, 10, 0, 0, $watermarkX, $watermarkY);
				}*/
				
                $this->img_r = $this->dst_r;
                $this->img_h = $h;
                $this->img_w = $w;
            }
            
            function createFile($output_filename = null) {
                if($this->ext == "JPG" OR $this->ext == "JPEG") {
                    imageJPEG($this->dst_r, $this->uploaddir.$output_filename.'.'.strtolower($this->ext), $this->quality);
                } elseif($this->ext == "PNG") {
                    imagePNG($this->dst_r, $this->uploaddir.$output_filename.'.'.strtolower($this->ext));
                } elseif($this->ext == "GIF") {
                    imageGIF($this->dst_r, $this->uploaddir.$output_filename.'.'.strtolower($this->ext));
                }
                $this->output = $this->uploaddir.$output_filename.'.'.strtolower($this->ext);
				//echo $this->output;
            }
            
            function setUploadDir($dirname) {
                $this->uploaddir = $dirname;
            }
            
            function flush() {
				$targetFolder = $this->uploaddir;
				$tempFile = $_FILES['Filedata']['tmp_name'];
				$targetPath = $targetFolder;
				$targetFile =  str_replace('//','/',$targetPath) . $_FILES['Filedata']['name'];
				$ext = strtoupper(pathinfo($targetFile, PATHINFO_EXTENSION));
				$fileEnc = substr(md5($tempFile),0,12).".".strtolower($ext);
				$targetFileEnc =  str_replace('//','/',$targetPath) . $fileEnc;
                imagedestroy($this->dst_r);
                unlink($targetFileEnc);
                //imagedestroy($this->img_r);
                
            }
            
        }


if (!empty($_FILES)) {
	$fileData = $_FILES['Filedata'];
	if ($fileData) {
		$tempFile   = $fileData['tmp_name'];
		$uploadDir  = $_SERVER['DOCUMENT_ROOT'] . $uploadDir;
		$targetFile = $uploadDir . $fileData['name'];
		
		
		// Validate the file type
		$fileTypes = array('png', 'jpg', 'gif','jpeg'); // Allowed file extensions
		$fileParts = pathinfo($fileData['name']);
		// Validate the filetype
		if (in_array(strtolower($fileParts['extension']), $fileTypes) && filesize($tempFile) > 0 && isImage($tempFile)) {
		
	
			if (isset($_REQUEST['id_section']) && ($_REQUEST['id_section']!="")){
				$file_id = $_REQUEST['id_section'];
				$section = 1;
			} else if (isset($_REQUEST['id_page']) && ($_REQUEST['id_page']!="")){
				$file_id = $_REQUEST['id_page'];
				$section = 0;
			}
			
			$id = $_REQUEST['id_page'];
			$file_modby = $_REQUEST['modby'];
			$file_moddate = $_REQUEST['moddate'];
			$tempFile = $_FILES['Filedata']['tmp_name'];
			$targetPath =  $uploadDir;
			$targetFile =  str_replace('//','/',$targetPath) . $_FILES['Filedata']['name'];
			$ext = strtoupper(pathinfo($targetFile, PATHINFO_EXTENSION));
			$fileEnc = substr(md5($tempFile),0,12).".".strtolower($ext);
			$targetFileEnc =  str_replace('//','/',$targetPath) . $fileEnc;
			
			move_uploaded_file($tempFile, $targetFileEnc);	
			$imgcompress = 1;//$_REQUEST['imgcompress'];
			
			echo  $targetFileEnc;
			
			
			if ($section==0){
					$insertSQL = sprintf("INSERT INTO xs_file (id_page,file_name,file_type,file_date,file_modby, file_imgcompress) VALUES (%s,%s,2,%s,%s,%s)",
			
                       GetSQLValueString($file_id, "int"),
                       GetSQLValueString(substr(md5($tempFile),0,12).".".strtolower($ext), "text"),
					   GetSQLValueString($file_moddate, "int"),
					   GetSQLValueString($file_modby, "text"),
					   GetSQLValueString($imgcompress, "int"));
						audit_trail($insertSQL,"sistem","","");
						mysqli_select_db( $exsite, $database_exsite); //echo $insertSQL;
						$Result1 = mysqli_query( $exsite, $insertSQL) or die(mysqli_error($exsite));
				
					
				
			} else if ($section==1)	{
				
				$insertSQL = sprintf("INSERT INTO xs_file (file_section_id,file_name,file_type,file_date,file_modby, file_imgcompress) VALUES (%s,%s,2,%s,%s,%s)",
			
                       GetSQLValueString($file_id, "int"),
                       GetSQLValueString(substr(md5($tempFile),0,12).".".strtolower($ext), "text"),
					   GetSQLValueString($file_moddate, "int"),
					   GetSQLValueString($file_modby, "text"),
					   GetSQLValueString($imgcompress, "int"));
						audit_trail($insertSQL,"sistem","","");
						mysqli_select_db( $exsite, $database_exsite); //echo $insertSQL;
						$Result1 = mysqli_query( $exsite, $insertSQL) or die(mysqli_error($exsite));
				
				
			}	
			
			
	    
	
		$image = new Image();
        $image->setFile($targetFileEnc);
        $image->setUploadDir($targetPath);
		
        $image->resize(1070);
        $image->createFile("l_".substr(md5($tempFile),0,12));
		$image->resize(640);
        $image->createFile("m_".substr(md5($tempFile),0,12));
        $image->resize(100);
        $image->createFile("s_".substr(md5($tempFile),0,12));
		
			
		if ($imgcompress==1){ // delete original image
			$image->flush();
		}
			
			// Save the file
			//move_uploaded_file($tempFile, $targetFileEnc);
			
		} else {
			// The file type wasn't allowed
			echo 'Invalid file type.';
		}
	}
}
?>