<?php
require_once(__DIR__.'/../../../Connections/exsite.php'); ?>
<?php
if (!isset($_SESSION)) {
	session_set_cookie_params(86400);
	session_start();
}
/*
UploadiFive
Copyright (c) 2012 Reactive Apps, Ronnie Garcia
*/
/*
IMPORTANT: This script requires the PHP GD library
*/
// Set the uplaod directory
$uploadDir = __DIR__.'/../../../userfiles/'.$_SESSION['account_id'].'/image';
function errorHandler($errno, $errstr, $errfile, $errline) {
	// In this script, the silently suppress any error generated by getimagesize
	// which will throw an error if the "image" isn't an image
	// ie doesn't have a valid width / height
    /* Don't execute PHP internal error handler */
    return true;
}
$old_error_handler = set_error_handler("errorHandler");
// Check if the file has a width and height
function isImage($tempFile) {
	// Get the size of the image
    $size = getimagesize($tempFile);
	if (isset($size) && $size[0] && $size[1] && $size[0] *  $size[1] > 0) {
		return true;
	} else {
		return false;
	}
}
function imageList($tempFile){
	$size = array_values(getimagesize($tempFile));
	return list($width, $height, $type, $attr) = $size;
}
function imageType($type){
	return image_type_to_mime_type($type);
}
if (!empty($_FILES)) {
	$fileData = $_FILES['Filedata'];
	if ($fileData) {
		$rand = rand();
		$tempFile   = $fileData['tmp_name'];
		//$uploadDir  = $_SERVER['DOCUMENT_ROOT'] . $uploadDir;
		$targetFile = $uploadDir."/".$rand."_".$fileData['name'];
		$targetFileHTTP = "http://".$_SERVER['SERVER_NAME'] . $uploadDir."/".$rand."_".$fileData['name'];
		// Validate the file type
		$fileTypes = array('jpg', 'jpeg', 'gif', 'png'); // Allowed file extensions
		$fileParts = pathinfo($fileData['name']);
		// Validate the filetype
		if (in_array(strtolower($fileParts['extension']), $fileTypes) && filesize($tempFile) > 0 && isImage($tempFile)) {
			
			
			
			// update xs_setup with relevant image info
			$updateSQL = sprintf("UPDATE xs_account_detail SET xs_account_detail_logo=%s, xs_account_detail_logo_width=%s, xs_account_detail_logo_height=%s, xs_account_detail_logo_type=%s, xs_account_detail_logo_attr=%s WHERE xs_account_detail_id = %s AND xs_account_detail_lang_id = %s",
				    GetSQLValueString($rand."_".$fileData['name'], "text"),
				    GetSQLValueString(imageList($targetFile)[0], "int"),
					GetSQLValueString(imageList($targetFile)[1], "int"),
					GetSQLValueString(imageList($targetFile)[2], "int"),
					GetSQLValueString(imageList($targetFile)[4], "text"),
					GetSQLValueString($_SESSION['account_id'], "int"),
					GetSQLValueString($_SESSION['lang_id'], "int"));
			mysqli_select_db( $exsite, $database_exsite); //echo $updateSQL;
			$Result1 = mysqli_query( $exsite, $updateSQL) or die(mysqli_error($exsite));
			
			//echo "Result:".$Result1;
            //echo $targetFile;
			
			// Save the file
			move_uploaded_file($tempFile, $targetFile);
			echo $rand."_".$fileData['name'];
		} else {
			// The file type wasn't allowed
			echo 'Invalid file type.';
		}
	}
}
?>