<?php $basedir = dirname(__FILE__);
require_once(__DIR__ . '/../../../Connections/exsite.php'); ?>
<?php
/*
UploadiFive
Copyright (c) 2012 Reactive Apps, Ronnie Garcia
*/

/*
IMPORTANT: This script requires the PHP GD library
*/
// Set the uplaod directory
$uploadDir = '/userfiles/smx/';


function errorHandler($errno, $errstr, $errfile, $errline)
{
	// In this script, the silently suppress any error generated by getimagesize
	// which will throw an error if the "image" isn't an image
	// ie doesn't have a valid width / height

	/* Don't execute PHP internal error handler */
	return true;
}

$old_error_handler = set_error_handler("errorHandler");

// Check if the file has a width and height
function isImage($tempFile)
{

	// Get the size of the image
	$size = getimagesize($tempFile);

	if (isset($size) && $size[0] && $size[1] && $size[0] *  $size[1] > 0) {
		return true;
	} else {
		return false;
	}
}
function imageList($tempFile)
{
	$size = array_values(getimagesize($tempFile));
	return list($width, $height, $type, $attr) = $size;
}
function imageType($type)
{
	return image_type_to_mime_type($type);
}

if (!empty($_FILES)) {

	$fileData = $_FILES['Filedata'];

	if ($fileData) {
		$tempFile   = $fileData['tmp_name'];
		$uploadDir  = $_SERVER['DOCUMENT_ROOT'] . $uploadDir;
		$targetFile = $uploadDir . $fileData['name'];
		$targetFileHTTP = "http://" . $_SERVER['SERVER_NAME'] . $uploadDir . $fileData['name'];

		// Validate the file type
		$fileTypes = array('jpg', 'jpeg', 'gif', 'png'); // Allowed file extensions
		$fileParts = pathinfo($fileData['name']);

		// Validate the filetype
		if (in_array(strtolower($fileParts['extension']), $fileTypes) && filesize($tempFile) > 0 && isImage($tempFile)) {



			$id = $_REQUEST['id_page'];
			$file_modby = $_REQUEST['modby'];
			$file_moddate = $_REQUEST['moddate'];

			$ext = strtoupper(pathinfo($targetFile, PATHINFO_EXTENSION));

			$insertSQL = sprintf(
				"INSERT INTO xs_file (id_page,file_name,file_type,file_date,file_modby) VALUES (%s,%s,2,%s,%s)",
				GetSQLValueString($id, "text"),
				GetSQLValueString(md5($tempFile) . "." . strtolower($ext), "text"),
				GetSQLValueString($file_moddate, "int"),
				GetSQLValueString($file_modby, "text")
			);
			echo $insertSQL;
			mysqli_select_db($exsite, $database_exsite);
			$Result1 = mysqli_query($exsite, $insertSQL) or die(mysqli_error($exsite));

			// Save the file
			$targetFileEnc =  str_replace('//', '/', $uploadDir) . md5($tempFile) . "." . strtolower($ext);
			//echo $tempFile;
			echo move_uploaded_file($tempFile, $targetFileEnc);
		} else {

			// The file type wasn't allowed
			echo 'Invalid file type.';
		}
	}
}
?>